version: '3.8'
services:
  movies:
    image: jyothsnafvn/paytmmoviesv1:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: jyothsnafvn/paytmtrainv1:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: jyothsnafvn/paytmdthv1:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: jyothsnafvn/paytmrechargev1:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
